GitHub:
  RemoteSSH: git@github.com:BRudow317/BRudow317.github.io.git
  RemoteHTTP: https://github.com/BRudow317/BRudow317.github.io.git
  Repository: https://github.com/BRudow317/BRudow317.github.io
  PublicURL: https://brudow317.github.io/
